import * as path from 'path';
import { Storage, resolveDbPath } from '../storage.js';
import type { CurrentTask } from '../task.js';

// ─── stop words ──────────────────────────────────────────────────────────────

const STOP_WORDS = new Set([
  'fix', 'add', 'update', 'the', 'a', 'in', 'for', 'on', 'to', 'from',
  'with', 'and', 'or', 'is', 'are', 'was', 'were', 'be', 'been', 'being',
  'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would', 'could',
  'should', 'may', 'might', 'shall', 'can', 'not', 'no', 'this', 'that',
  'these', 'those', 'it', 'its',
  // Spanish
  'el', 'la', 'los', 'las', 'un', 'una', 'en', 'de', 'del', 'al',
  'con', 'por', 'para', 'que', 'como', 'se', 'su', 'sus',
]);

// ─── types ───────────────────────────────────────────────────────────────────

export interface BriefSymbol {
  name: string;
  file: string;
  type: string;
  line: number;
}

export interface BriefDoc {
  path: string;
  summary: string;
}

export interface BriefResult {
  markdown: string;
  tokens: number;
  symbols: BriefSymbol[];
  docs: BriefDoc[];
  gotchas: BriefDoc[];
}

// ─── helpers ─────────────────────────────────────────────────────────────────

function countTokens(text: string): number {
  return Math.ceil(text.length / 4);
}

function extractTerms(description: string): string[] {
  const words = description
    .toLowerCase()
    .split(/[\s\-_/\\.,;:!?'"()\[\]{}]+/)
    .filter(Boolean)
    .filter(w => !STOP_WORDS.has(w) && w.length > 2);

  // Deduplicate, sort by length descending (longer = more specific)
  const unique = [...new Set(words)].sort((a, b) => b.length - a.length);
  return unique.slice(0, 3);
}

function compose(
  task: CurrentTask,
  symbols: BriefSymbol[],
  docs: BriefDoc[],
  gotchas: BriefDoc[],
  timestamp: string,
): string {
  const lines: string[] = [
    '## NCA Brief — light',
    `**Task**: ${task.description}`,
    '',
  ];

  if (symbols.length > 0) {
    lines.push('### Relevant symbols');
    for (const s of symbols) {
      lines.push(`- \`${s.name}\` in ${path.basename(s.file)} — ${s.type}`);
    }
    lines.push('');
  }

  if (docs.length > 0) {
    lines.push('### Related docs');
    for (const d of docs) {
      const summary = d.summary ? ` — ${d.summary}` : '';
      lines.push(`- ${d.path}${summary}`);
    }
    lines.push('');
  }

  if (gotchas.length > 0) {
    lines.push('### Known gotchas');
    for (const g of gotchas) {
      const summary = g.summary ? ` — ${g.summary}` : '';
      lines.push(`- ${g.path}${summary}`);
    }
    lines.push('');
  }

  const tokenCount = countTokens(lines.join('\n'));
  lines.push('---');
  lines.push(`*Generated by NCA · ${tokenCount} tokens · ${timestamp}*`);

  return lines.join('\n');
}

// ─── main ────────────────────────────────────────────────────────────────────

export function generateBrief(opts: {
  task: CurrentTask;
  repoRoot: string;
  vaultRoot?: string;
}): BriefResult {
  const { task, repoRoot, vaultRoot } = opts;
  const timestamp = new Date().toISOString();

  // Step 1: extract search terms
  const terms = extractTerms(task.description);

  // Open repo DB
  const dbPath = resolveDbPath(repoRoot);
  const storage = new Storage(dbPath);

  let symbols: BriefSymbol[] = [];
  let docs: BriefDoc[] = [];
  let gotchas: BriefDoc[] = [];

  try {
    // Step 2: search symbols in the graph
    const seenNames = new Set<string>();
    const candidateSymbols: BriefSymbol[] = [];

    for (const term of terms) {
      const nodes = storage.search(term);
      for (const n of nodes) {
        if (seenNames.has(n.name)) continue;
        seenNames.add(n.name);
        candidateSymbols.push({
          name: n.name,
          file: n.file,
          type: n.type,
          line: n.line,
        });
      }
      if (candidateSymbols.length >= 6) break;
    }

    // Sort by complexity descending as a PageRank proxy (simpler, no graph build)
    // and take top 3
    symbols = candidateSymbols.slice(0, 3);

    // Step 3: search docs in vault (if vaultRoot available)
    if (vaultRoot) {
      const vaultDbPath = resolveDbPath(vaultRoot);
      let vaultStorage: Storage | null = null;
      try {
        vaultStorage = new Storage(vaultDbPath);
        const seenDocIds = new Set<string>();

        for (const term of terms) {
          const results = vaultStorage.vaultSearch(term, {}, 5);
          for (const r of results) {
            // EXCLUDE docs with status 'obsoleto'
            if (r.status === 'obsoleto') continue;
            if (seenDocIds.has(r.id)) continue;
            seenDocIds.add(r.id);
            docs.push({
              path: r.path,
              summary: r.summary ?? r.snippet ?? '',
            });
          }
          if (docs.length >= 4) break;
        }

        docs = docs.slice(0, 2);

        // Step 4: gotcha via doc_code_edges
        if (symbols.length > 0) {
          const seenGotchaIds = new Set(seenDocIds);
          for (const sym of symbols) {
            const symDocs = storage.getDocsBySymbol(sym.name);
            for (const sd of symDocs) {
              // Check status via vaultGet
              const noteDetail = vaultStorage.vaultGet(sd.file);
              if (!noteDetail) continue;
              if (noteDetail.status === 'obsoleto') continue;
              if (seenGotchaIds.has(noteDetail.id)) continue;
              seenGotchaIds.add(noteDetail.id);
              gotchas.push({
                path: sd.file,
                summary: noteDetail.summary ?? sd.excerpt ?? '',
              });
              break; // max 1 gotcha
            }
            if (gotchas.length >= 1) break;
          }
        }
      } catch {
        // vault DB not available — skip silently
      } finally {
        vaultStorage?.close();
      }
    }
  } finally {
    storage.close();
  }

  // Step 5: compose and verify budget
  let markdown = compose(task, symbols, docs, gotchas, timestamp);
  let tokens = countTokens(markdown);

  if (tokens > 300) {
    // Trim: reduce symbols to 2
    symbols = symbols.slice(0, 2);
    markdown = compose(task, symbols, docs, gotchas, timestamp);
    tokens = countTokens(markdown);
  }

  if (tokens > 300) {
    // Trim: reduce docs to 1
    docs = docs.slice(0, 1);
    markdown = compose(task, symbols, docs, gotchas, timestamp);
    tokens = countTokens(markdown);
  }

  if (tokens > 300) {
    // Trim: eliminate gotcha
    gotchas = [];
    markdown = compose(task, symbols, docs, gotchas, timestamp);
    tokens = countTokens(markdown);
  }

  if (tokens > 300) {
    // Still over budget — warn but return
    markdown = markdown + '\n\n[WARN: brief exceeds 300 token budget]';
    tokens = countTokens(markdown);
  }

  return { markdown, tokens, symbols, docs, gotchas };
}
